apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app-service
  labels:
    app: {{ .Release.Name }}-app-service
spec:
#  type: NodePort
  ports:
  - protocol: TCP
    port: 3003
    targetPort: 3003
  selector:
    app: {{ .Release.Name }}-app-pod