apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nginx-rp-service
  labels:
    app: {{ .Release.Name }}-nginx-rp-service
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 443
    targetPort: 443
    nodePort: 30443
    name: https
  selector:
    app: {{ .Release.Name }}-nginx-rp-pod