apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-nginx-rp-deploy
  namespace: default
spec:
  replicas: {{ .Values.nginx-rp.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-nginx-rp-pod
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-nginx-rp-pod
    spec:
      containers:
      - name: {{ .Release.Name }}-nginx-rp-container
        image: nginx:latest
        ports:
          - containerPort: 80
            name: http
            protocol: TCP
          - containerPort: 443
            name: https
            protocol: TCP
        volumeMounts:
        - name: {{ .Release.Name }}-nginx-rp-config
          mountPath: /etc/nginx/conf.d
        - name: nginx-rp-secret
          mountPath: /etc/nginx/ssl
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
      volumes:
      - name: {{ .Release.Name }}-nginx-rp-config
        configMap:
          name: {{ .Release.Name }}-nginx-rp-config
      - name: nginx-rp-secret
        secret:
          secretName: nginx-rp-secret