apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-postgres-deploy
  labels:
    app: {{ .Release.Name }}-postgres-deploy
spec:
  replicas: {{ .Values.db.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-postgres-pod
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-postgres-pod
    spec:
      containers:
      - name: {{ .Release.Name }}-postgres-container
        image: postgres:13-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: db-cred
              key: db_name
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-cred
              key: db_user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-cred
              key: db_pass
        volumeMounts:
        - name: {{ .Release.Name }}-postgres-storage
          mountPath: /var/lib/postgresql/data
        - name: sfdata
          mountPath: "/etc/sfdata"
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
      volumes:
      - name: {{ .Release.Name }}-postgres-storage
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-postgres-pvc
      - name: sfdata
        secret:
          secretName: db-cred