apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgres-service
  labels:
    app: {{ .Release.Name }}-postgres-service
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: {{ .Release.Name }}-postgres-pod
