apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "myapp.fullname" . }}-app
  labels:
    app: {{ include "myapp.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "myapp.fullname" . }}
      tier: backend
  template:
    metadata:
      labels:
        app: {{ include "myapp.fullname" . }}
        tier: backend
    spec:
      containers:
        - name: app
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          ports:
            - containerPort: {{ .Values.app.port }}
          volumeMounts:
            - name: app-volume
              mountPath: /app
          command: ["/bin/sh", "-c"]
          args: ["python manage.py migrate && python manage.py runserver 0.0.0.0:{{ .Values.app.port }}"]
          env:
            - name: DB_HOST
              value: {{ .Values.app.env.DB_HOST }}
            - name: DB_NAME
              value: {{ .Values.app.env.DB_NAME }}
            - name: DB_USER
              value: {{ .Values.app.env.DB_USER }}
            - name: DB_PASS
              value: {{ .Values.app.env.DB_PASS }}
      volumes:
        - name: app-volume
          hostPath:
            path: ./app
