apiVersion: v1
kind: Service
metadata:
  name: {{ include "myapp.fullname" . }}-db
  labels:
    app: {{ include "myapp.fullname" . }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.db.port }}
      targetPort: {{ .Values.db.port }}
  selector:
    app: {{ include "myapp.fullname" . }}
    tier: database
