apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deploy
  labels:
    app: django-deploy
spec:
  selector:
    matchLabels:
      app: django-pod
  replicas: 2 # runs 2 pods created with template
  template:
    metadata:
      labels:
        app: django-pod
    spec:
      containers:
      - name: django-container
        image: eukhlg/django:latest
        ports:
        - containerPort: 3003
        volumeMounts:
        - name: sfdata
          mountPath: "/etc/sfdata"
          readOnly: true
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: db-cred
              key: db_host
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-cred
              key: db_name
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-cred
              key: db_user
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: db-cred
              key: db_pass
        command: ["sh", "-c"]
        args: ["python manage.py migrate && python manage.py runserver 0.0.0.0:3003"]
      volumes:
      - name: sfdata
        secret:
          secretName: db-cred
