apiVersion: v1
kind: Service
metadata:
  name: nginx-rp-service
  labels:
    app: nginx-rp-service
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: http
  - protocol: TCP
    port: 443
    targetPort: 443
    name: https
  selector:
    app: nginx-rp-pod