apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-rp-config
  namespace: default
data:
  nginx.conf: |
    events {
      worker_connections 1024;
    }

    http {
        server {
          listen 80;

          # Example: Proxy requests to a service within the cluster
          location / {
            proxy_pass http://django-service.default.svc.k8s.app.local:3003;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
          }

          # Optional: Add more locations for different services or paths
          # location /other-path/ {
          #   proxy_pass http://another-service.default.svc.cluster.local:9090;
          # }
        }
      }