apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 2
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: db-cred
              key: db_name
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-cred
              key: db_user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-cred
              key: db_pass
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        - name: sfdata
          mountPath: "/etc/sfdata"
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
      - name: sfdata
        secret:
          secretName: db-cred